name: Deploy Wiki Pages to Server

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USER }}
          key: ${{ secrets.DEPLOY_SERVER_SSH_KEY }}
          script: |
            cd /root/MyWiki
            git pull origin master

            cp -r hugo/* /root/hugo/site/content/


            find /root/hugo/site/content -type f -name "*.md" -exec sed -i '/^published:/d' {} \;

            find /root/hugo/site/content/posts -type f -name "*.md" -exec bash -c 'if ! grep -q "^type:" "$1"; then sed -i "0,/^---$/s/^---$/&\ntype: post/" "$1"; fi' _ {} \;
            find /root/hugo/site/content/projects -type f -name "*.md" -exec bash -c 'if ! grep -q "^type:" "$1"; then sed -i "0,/^---$/s/^---$/&\ntype: page/" "$1"; fi' _ {} \;
